### ISSUE TITLE
Any plans to release nuget package?

### ISSUE THREAD

**Issue by mdrgeniebelt** [eiximenis/Serilog.Logfmt#1]
Hello :) 

Like in the name of the issue, are you planning to release this as a nuget package? Seems like in .net we are way behind other languages when it comes to supporting logfmt :(

**Comment by eiximenis** [comment]
Hi!
Sorry for the delay :)

I've published a nuget package: https://www.nuget.org/packages/Serilog.Logfmt/ :)

Hope this helps!

PS: 1.0.1 and 1.0.0 have the same code, but 1.0.1 has sourcelink enabled.
