### ISSUE TITLE
Escape or transform double quotes in msg

### ISSUE THREAD

**Issue by dg-eparizzi** [eiximenis/Serilog.Logfmt#2]
If the message contains double quotes the output ends up being something like this:

```
ts=2021-05-25T15:17:22.3560941Z level=info env_name=Development source_context=Microsoft.Hosting.Lifetime msg="Hosting environment: "Development""
````
This is invalid logfmt.

Not sure what's the best option here, but I'd say transforming double quotes into single quotes should be enough.

**Comment by eiximenis** [comment]
Hi @dg-eparizzi!

I submitted a patch for this. By default double quotes inside the message are replaced by a single quote.
However, you can configure this behavior (do nothing, remove double quotes, escape them with `\"` or replace by single quotes by using the `OnDoubleQuotes` config method:

```cshap
.WriteTo.Console(formatter: new LogfmtFormatter(opt => opt.OnDoubleQuotes(q => q.Escape()));
```

Version `1.0.2` is published with this change.
